/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finansial;
import java.awt.event.KeyEvent;
import java.util.List;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author daffa
 */

public class KasirSmega extends javax.swing.JFrame {
    int subtotalbelanja,baris,jumlahbeli,subtotal;
     boolean baristerpilih;
//    DefaultTableModel datamodel;
    /**
     * Creates new form KasirSmega
     */
    
    DefaultTableModel model;
    
    public KasirSmega() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbbarang = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbltotal = new javax.swing.JLabel();
        txtjml = new javax.swing.JTextField();
        lblharga = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpenjualan = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logosmegamart.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SMEGA MART KASIR");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SMK NEGERI 1 PURBALINGGA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(15, 15, 15)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 0, 0));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("nama barang");

        cmbbarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Barang", "ELEKTRONIK", "Televisi", "Kulkas", "Ac", "Lampu", "PAKAIAN", "celana", "rok", "jubah", "Kerudung", "PERALATAN RUMAH TANGGA", "Sendok", "Piring", "Kompor", " ", " ", " " }));
        cmbbarang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbbarangItemStateChanged(evt);
            }
        });
        cmbbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbbarangActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Rp.");

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 153, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Jumlah");

        lbltotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbltotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbltotal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 3, true));

        txtjml.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        txtjml.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));
        txtjml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjmlActionPerformed(evt);
            }
        });
        txtjml.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtjmlKeyPressed(evt);
            }
        });

        lblharga.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblharga.setText("...");

        tblpenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nama barang", "harga satuan", "jumlah beli", "subtotal"
            }
        ));
        tblpenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpenjualanMouseClicked(evt);
            }
        });
        tblpenjualan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblpenjualanKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblpenjualan);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Rp.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(79, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblharga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(cmbbarang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(64, 64, 64)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbltotal, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                            .addComponent(txtjml))
                        .addGap(77, 77, 77))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtjml, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(10, 10, 10)
                .addComponent(cmbbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblharga, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(295, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtjmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjmlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjmlActionPerformed

    private void cmbbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbbarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbbarangActionPerformed

    private void cmbbarangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbbarangItemStateChanged
        // TODO add your handling code here:
        switch(cmbbarang.getSelectedIndex()){
            case 0:
            lblharga.setText("...");
            break;
            case 1:
            lblharga.setText("...");
            break;
            case 2:
            lblharga.setText("3330000");
            break;
            case 3:
            lblharga.setText("2000000");
            break;
            case 4:
            lblharga.setText("1000000");
            break;
            case 5:
            lblharga.setText("15000");
            break;
            case 6:
            lblharga.setText("...");
            break;
            case 7:
            lblharga.setText("65000");
            break;
            case 8:
            lblharga.setText("105000");
            break;
            case 9:
            lblharga.setText("190000");
            break;
            case 10:
            lblharga.setText("25000");
            break;
            case 11:
            lblharga.setText("...");
            break;
            case 12:
            lblharga.setText("6000");
            break;
            case 13:
            lblharga.setText("15000");
            break;
            case 14:
            lblharga.setText("320000");
            break;
            default :
            lblharga.setText("0 ");
            break;
        }
        txtjml.requestFocus();
        
     
        
    }//GEN-LAST:event_cmbbarangItemStateChanged

    private void txtjmlKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjmlKeyPressed
        // TODO add your handling code here:
         DefaultTableModel dataModel = (DefaultTableModel)tblpenjualan.getModel(); 
        List list = new ArrayList<>();
        tblpenjualan.setAutoCreateColumnsFromModel(true);
        list.add(cmbbarang.getSelectedItem().toString());
        list.add(lblharga.getText());
        list.add(txtjml.getText());
        
        if(evt.getKeyCode()== KeyEvent.VK_ENTER) {
            if(baristerpilih) {
                 btnEditClick();
         }else{
        subtotal();
        list.add(String.valueOf(subtotalbelanja));
        dataModel.addRow(list.toArray());
        bersihkanlayar();
        total();
        //sum();
    }
        }
       if(evt.getKeyCode()== KeyEvent.VK_DELETE){
           if(baristerpilih){
             int baris = tblpenjualan.getSelectedRow();
             dataModel.removeRow(baris);
               KeyDelete();
           }
        tblpenjualan.clearSelection();
        baristerpilih=false;
      }
            
    }//GEN-LAST:event_txtjmlKeyPressed

    private void tblpenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpenjualanMouseClicked
        // TODO add your handling code here:
       mouseClick();
//       jumlahbaris();
//       cekbaristerpilih();
////        int baris = tblpenjualan.getSelectedRow();
////       
////       String namabarang = (String) tblpenjualan.getValueAt(baris, 0);
////       String hargasatuan = (String) tblpenjualan.getValueAt(baris, 1);
////       String jmlbeli= (String) tblpenjualan.getValueAt(baris, 2);
////       
////       String Subtotal = (String)tblpenjualan.getValueAt(baris, 3);
////       int row = baris;
////       
////       tblpenjualan.setValueAt(namabarang,row,0);
////       tblpenjualan.setValueAt(hargasatuan,row,1);
////       tblpenjualan.setValueAt(jmlbeli,row,2);
////       
////       cmbbarang.setSelectedItem(namabarang.toString());
////       txtjml.setText(jmlbeli);
////       
////        if(namabarang.equals("ice cream")){
////            cmbbarang.setSelectedIndex(1);
////        }else if (namabarang.equals("chitato")){
////            cmbbarang.setSelectedIndex(2);
////        }else if (namabarang.equals("sikat Gigi")){
////            cmbbarang.setSelectedIndex(3);
////        }else if (namabarang.equals("close up")){
////            cmbbarang.setSelectedIndex(4);
////        }else{
////            cmbbarang.setSelectedIndex(0);
////        }
////        
////        lblharga.setText(hargasatuan);
////        txtjml.setText(jmlbeli);
////        lbltotal.setText(Subtotal);
////    
    }//GEN-LAST:event_tblpenjualanMouseClicked

    private void tblpenjualanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblpenjualanKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_BACK_SPACE){
        int selectedRow = tblpenjualan.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblpenjualan.getModel();
        model.removeRow(selectedRow);
        
       
        }
    }//GEN-LAST:event_tblpenjualanKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KasirSmega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KasirSmega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KasirSmega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KasirSmega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KasirSmega().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbbarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblharga;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JTable tblpenjualan;
    private javax.swing.JTextField txtjml;
    // End of variables declaration//GEN-END:variables

    private int subtotal() {
     //To change body of generated methods, choose Tools | Templates.
     int jmlbeli,hargasatuan;
     jmlbeli = Integer.valueOf(txtjml.getText());
     hargasatuan = Integer.valueOf(lblharga.getText());
     subtotalbelanja =  hargasatuan * jmlbeli;
     lbltotal.setText(String.valueOf(subtotalbelanja));
     return subtotalbelanja;
    }
    
       

    private void bersihkanlayar() {
      //To change body of generated methods, choose Tools | Templates.
      txtjml.setText("");
    lblharga.setText("0");
    //lbltotal.setText("");
    cmbbarang.setSelectedIndex(0);
    }
    

    private void sum() {
     //To change body of generated methods, choose Tools | Templates.
        DefaultTableModel dataModel = (DefaultTableModel) tblpenjualan.getModel();
        int jumlah = dataModel.getRowCount();
        int sumBerat =0;
        int sumTinggi =0;
        int sumTotal =0;
        
        for (int i = 0; i < jumlah; i++) {
            int dataBerat = Integer.valueOf(dataModel.getValueAt(i, 1).toString());
            int dataTinggi = Integer.valueOf(dataModel.getValueAt(i, 2).toString());
            int dataTotal = Integer.valueOf(dataModel.getValueAt(i, 3).toString());
            sumBerat += dataBerat;
            sumTinggi += dataTinggi;
            sumTotal += dataTotal;
        }
        //jumlah_data.setText(Integer.toString(jumlah));
        //sum_berat.setText(Double.toString(sumBerat));
        //sum_tinggi.setText(Double.toString(sumTinggi)); 
        lbltotal.setText(Integer.toString(sumTotal));
       // txtdata.setText(String.valueOf(sumBerat1));
    }

    private void total() {
     //To change body of generated methods, choose Tools | Templates.
     DefaultTableModel dataModel = (DefaultTableModel)tblpenjualan.getModel();
        int jumlah = dataModel.getRowCount();
        int sumTotal =0;
        
        for (int i = 0; i < jumlah; i++) {
            int dataTotal = Integer.valueOf(dataModel.getValueAt(i,3).toString());
            sumTotal += dataTotal;
            lbltotal.setText(Integer.toString(sumTotal));
        }
        //jumlah_data.setText(Integer.toString(jumlah));
        //sum_berat.setText(Double.toString(sumBerat));
        //sum_tinggi.setText(Double.toString(sumTinggi)); 
        lbltotal.setText(Integer.toString(sumTotal));
    }

    private void mouseClick() {
        //To change body of generated methods, choose Tools | Templates.
      baris = tblpenjualan.getSelectedRow();
      baristerpilih=true;
      
      String namabarang = (String) tblpenjualan.getValueAt(baris, 0);
      String hargasatuan = (String) tblpenjualan.getValueAt(baris, 1);
      String jmlbeli = (String) tblpenjualan.getValueAt(baris, 2);
      
      cmbbarang.setSelectedItem(namabarang.toString());
      lblharga.setText(hargasatuan);
      txtjml.setText(jmlbeli);
      
    }                 

    private void btnEditClick() {
        DefaultTableModel dataModel = (DefaultTableModel) tblpenjualan.getModel();
        int baris = tblpenjualan.getSelectedRow();
        
        String namabarang = (String) cmbbarang.getSelectedItem();
        String hargasatuan = (String) lblharga.getText();
        String jmlbeli = (String) txtjml.getText();
                  
        subtotal();
        
        dataModel.setValueAt (namabarang,baris,0);
        dataModel.setValueAt (hargasatuan,baris,1);
        dataModel.setValueAt (jmlbeli,baris,2);        
        dataModel.setValueAt (subtotalbelanja,baris,3);
        
        total();
        bersihkanlayar();
        tblpenjualan.clearSelection();
        baristerpilih=false;
        
          
        }

    private void KeyDelete() {
        //To change body of generated methods, choose Tools | Templates.
        cmbbarang.setSelectedIndex(0);
            lblharga.setText("0");
            lbltotal.setText("");
            txtjml.setText("");
            
            
            
            tblpenjualan.clearSelection();
            baristerpilih=false;
    }
        
    }              
    

